### ISSUE TITLE
Missing Webpack declaration in /dist/**/*.d.ts

### ISSUE THREAD

**Issue by Xceno** [aurelia/loader-webpack#36] opened 2017-11-23 12:51 UTC
**I'm submitting a bug report**

* **Library Version:** 2.1.0

**Please tell us about your environment:**
* **Operating System:** Windows 10

* **Node Version:** 6.9.1

* **NPM Version:** 3.10.8

* **yarn Version:** 1.3.2

* **Webpack:** 3.4.1

* **Browser:** all

* **Language:** TypeScript 2.6.1

**Current behavior:**
The type definition is missing a Webpack reference.

>[at-loader] Checking finished with 1 errors
>[at-loader] ./node_modules/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.d.ts:31:51
    TS2503: Cannot find namespace 'Webpack'.
[Link to source](https://github.com/aurelia/loader-webpack/blob/master/dist/commonjs/aurelia-loader-webpack.d.ts#L31)

**Expected/desired behavior:**

* **Reproducing the error**
  * Download the source of this repo
  * open any `/dist/**/aurelia-loader-webpack.d.ts`
  * It will complain about the missing Webpack namespace at line 31.

* **What is the expected behavior?**
The typings should be able to resolve the Webpack namespace

* **What is the motivation / use case for changing the behavior?**
Apps that use this package nonetheless compile successfully, but it's confusing to see this error all the time.
It seems to be easily resolved by copying `webpack-hot-interface.d.ts` into `dist/**/`

**Comment by jods4** [comment] 2017-11-23 20:44
This is a bug in `at-loader`.
We worked around it by temporarily disabling the types in `aurelia-webpack-plugin@2.0.0-rc.4`.
I suspect you use RC3 or before (latest is RC5).

**Comment by jods4** [comment] 2017-11-23 20:45
Closing as a duplicate of aurelia/webpack-plugin#118

**Closed as completed by jods4** 2017-11-23 20:45 UTC

**Comment by Xceno** [comment] 2017-11-24 07:59
Thanks for pointing me in the right direction once again!
